---
- hosts: Test-Servers
  sudo: yes
  tasks:
  - name: Install latest version of Apache
    yum:
      name: httpd
      state: latest
  - name: Ensure that list of Packages are already present
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - httpd
        - httpd-tools
  - name: Start the httpd service
    service:
      name: httpd
      state: started
  - name: copy the application code to remote server to print hello world and bounce apache to display it
    template:
      src: /etc/ansible/HelloWorld.html
      dest: /var/www/html/index.html
    notify: 
    - restart apache
  handlers:
  - name: restart apache
    service:
      name: httpd
      state: restarted
